# @server = https://texai-supreme-potato-4wgxxr65f5g5x-8080.preview.app.github.dev
@server = https://sem8.onrender.com
@apiserver = {{server}}/api/curso
###

GET {{server}}
###
GET {{server}}/codigo
###
GET {{server}}/nombre-completo

###
GET {{apiserver}}/listar

###
POST {{apiserver}}/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=Inteligencia+Artificial&creditos=4

###
DELETE {{apiserver}}/eliminar
Content-Type: application/x-www-form-urlencoded

id=54